### ISSUE TITLE
DeprecationWarning: Implementing implicit namespace packages with setuptools 67.3.1

### ISSUE THREAD

**Issue by phillipuniverse** [pycountry/pycountry#153]
Here's the stack trace of the deprecation warning:

```
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pycountry/__init__.py:10: in <module>
    import pkg_resources
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3256: in <module>
    @_call_aside
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3231: in _call_aside
    f(*args, **kwargs)
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3282: in _initialize_master_working_set
    tuple(dist.activate(replace=False) for dist in working_set)
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:3282: in <genexpr>
    tuple(dist.activate(replace=False) for dist in working_set)
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:2803: in activate
    declare_namespace(pkg)
../../../Library/Caches/pypoetry/virtualenvs/{{cookiecutter-service-name}}-DDHQZerL-py3.11/lib/python3.11/site-packages/pkg_resources/__init__.py:2297: in declare_namespace
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
make: *** [test] Error 4
```

67.2.0 does not have this DeprecationWarning.

Maybe related - https://github.com/pypa/setuptools/issues/3826

**Comment by bastimeyer** [comment]
setuptools 67.5.0 has added another `DeprecationWarning` when loading the `pkg_resources` package:

> pkg_resources is deprecated as an API

https://setuptools.pypa.io/en/latest/history.html#v67-5-0

----

`pkg_resources` needs to be replaced with `importlib`:
https://docs.python.org/3/library/importlib.html

`importlib.metadata` is only available since py38, but the `importlib_metadata` package from PyPI can be used on py37 as a fallback, which is the minimum version required by pycountry.
https://pypi.org/project/importlib-metadata/
https://github.com/flyingcircusio/pycountry/blob/83c38348a1e76f0a68c3a262c6fc0e8beda8b706/pyproject.toml#L36

----

The following needs to be fixed:

https://github.com/flyingcircusio/pycountry/blob/83c38348a1e76f0a68c3a262c6fc0e8beda8b706/src/pycountry/__init__.py#L9-L22

#155 has already been opened, but it doesn't properly remove `pkg_resources` and doesn't use `importlib_metadata`.

**Comment by bastimeyer** [comment]
The `DepecationWarning` that gets raised by `pkg_resources` got updated again in `setuptools 68.0.0`:
https://setuptools.pypa.io/en/stable/history.html#v68-0-0

> ```
> .../lib/python3.11/site-packages/pycountry/__init__.py:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>    import pkg_resources
> ```

Could one of the maintainers please have a look at this issue and the open pull request?
@ctheune @nschimmoller
