### ISSUE TITLE
Missing country properties should be "" (empty string) or at least None

### ISSUE THREAD

**Issue by DleanJeans** [pycountry/pycountry#30]
Properties like `common_name` or  `official_name` are not available for many countries and territories raising `AttributeError` when accessed.

Current workaround is:
```
official_name = getattr(country, 'official_name', '')
common_name = getattr(country, 'common_name', '')

if official_name:
  print(official_name)
if common_name:
  print(common_name)
```
If those properties are `""` or `None` by default, the above code could be shorten to:
```
if country.official_name:
  print(country.official_name)
if country.common_name:
  print(country.common_name)
```

**Comment by wobagi** [comment]
I stumbled upon this issue right after using pycountry for the very first time. I wanted to print selected attributes for all the countries so I wrote a simple iteration with basic attributes I've seen in one of the official examples.

```
for c in pycountry.countries:
    print(c.alpha_2, c.name, c.official_name)
```

And got AttributeError. It made me think the library is broken. Sure it is easy to prevent with try/except etc and I quickly found out what was going on, however I think a less skilled user will not be able to understand the error, so I second the @DleanJeans' suggestion. Especially since subdivisions work this way and list None when there is no parent_code.
Other than that, I found the lib very nice and useful. Thanks.
