### ISSUE TITLE
Support for information if country name should be prefixed with "the"

### ISSUE THREAD

**Issue by m-aciek** [pycountry/pycountry#54]
Hi, thank you for your work on this package.

We'd like to request a feature: support for information if country name should be prefixed with "the" article.

The rules for English are below:
http://www.cambridge.org/grammarandbeyond/newsletter/2011/11/using-the-with-the-names-of-countries

If you would give us a green light, we would be keen to implement it.

**Comment by nschimmoller** [comment]
@m-aciek anybody is free to make a pull request to pycountry if you'd like an enhancement to be considered. Please keep in mind though that changing any of the ISO files is off limits due to our data update policy 

> Data update policy
> No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people

For now I am going to close this issue as it is very old. If you're still interested in this please open up a new Issue or create a PR :)
